/**
 * Shared helper functions for workflow routes
 */
import { prisma } from '../../lib/prisma.js';
import { writeWorkflowFiles, commitAndPush } from '../../lib/github.js';

/**
 * Workflow data required for GitHub commit
 */
export interface WorkflowForGitHub {
    id: string;
    name: string;
    description: string | null;
    githubRepo: string | null;
    githubBranch: string | null;
    githubPath: string | null;
    localPath: string | null;
    githubCredentialId: string | null;
    pythonWorkflow: string | null;
    pythonActivities: string | null;
    pythonRequirements: string | null;
}

/**
 * Result of GitHub commit operation
 */
export interface GitHubCommitResult {
    success: boolean;
    commitSha?: string;
    error?: string;
}

/**
 * Helper to commit workflow to GitHub if configured
 */
export async function commitWorkflowToGitHub(
    workflow: WorkflowForGitHub
): Promise<GitHubCommitResult> {
    if (!workflow.githubRepo || !workflow.localPath || !workflow.githubCredentialId) {
        return { success: true }; // Not configured, skip
    }

    // Get credentials
    const credential = await prisma.dataSource.findUnique({
        where: { id: workflow.githubCredentialId },
    });

    if (!credential || credential.type !== 'github') {
        return { success: false, error: 'GitHub credential not found' };
    }

    // Prepare files
    const files: Record<string, string> = {
        'workflow.py': workflow.pythonWorkflow || '',
        'activities.py': workflow.pythonActivities || '',
        'requirements.txt': workflow.pythonRequirements || '',
        'README.md': `# ${workflow.name}\n\n${workflow.description || 'A Twiddle workflow.'}\n\nGenerated by Twiddle.`,
    };

    // Write files to local repo
    const workflowPath = workflow.githubPath || '';
    await writeWorkflowFiles(workflow.localPath, workflowPath, files);

    // Commit and push
    const commitMessage = `Update workflow: ${workflow.name}`;
    const result = await commitAndPush(
        workflow.localPath,
        commitMessage,
        workflow.githubBranch || 'main',
    );

    if (result.success && result.commitSha) {
        // Update last commit SHA
        await prisma.workflow.update({
            where: { id: workflow.id },
            data: { lastCommitSha: result.commitSha },
        });
    }

    return result;
}
